config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

Qoloquio::Application.routes.draw do

  match '/auth/:provider/callback' => 'users#create' # omniauth
  get "auth/failure" => "home#auth_failure"

  get '/logout' => 'sessions#destroy', as: 'logout'

  # admin path:
  get 'admin' => 'admin#index'

  resources :embedded, only: [:show]

  resources :comments do
    member do
      get :count
    end
  end

  resources :ads do
    member do
      put :visited
    end
  end

  resources :videos do
    member do
      get :tl
    end
  end

  namespace :admin do
    resources :videos, path: "programas" do
      member do
        get :embed
      end
    end
    resources :ads
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :preferences
    resources :segmentos
  end

  # sidekiq:
  mount Sidekiq::Web, at: "/sidekiq_web", :constraints => AdminConstraint.new

  root to: 'home#index'

  match '*a', :to => 'application#routing_error'
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  
  attr_accessible :key,
                  :value,
                  :descripcion

  serialize :value

  # validations:
    validates :key, :presence => true,
                    :uniqueness => true
    validates :value, :presence => true

  # methods:
    def evalued_value
      @evalue_value ||= eval(self.value)
    end

end

app/controllers/admin/preferences_controller.rb
# encoding: utf-8
class Admin::PreferencesController < AdminController
  
  before_filter :set_place

  def index
    @preferences = Preference.all
  end

  def new
    @preference = Preference.new
  end

  def create
    @preference = Preference.new params[:preference]
    if @preference.save
      flash["alert-success"] = "preferencia creada."
      redirect_to action: :index
    else
      flash["alert-error"] = "preferencia no creada."
      render :new
    end
  end

  def edit
    @preference = Preference.find params[:id]
    render :new
  end

  def update
    if @preference = Preference.update(params[:id], params[:preference])
      flash["alert-success"] = "preferencia actualizada."
      redirect_to action: :index
    else
      flash["alert-error"] = "preferencia no actualizada."
      render :new
    end
  end

  private

    def set_place
      @place = "preferences"      
    end

end

app/views/admin/preferences/_form.html.erb
<div class="align_center">
  <h2>preferencia</h2>
</div>

<%= form_for [:admin, @preference] do |f| %>
  
  <% if @preference.errors.any? %>
    <div class="alert alert-error">
      <h4><%= pluralize @preference.errors.count, "error", "errores" %>:</h4>
      <ul>
        <% @preference.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key, "llave" %>
    <%= f.text_field :key, :required => true %>
  </div>

  <div class="field">
    <%= f.label :value, "valor" %>
    <%= f.text_area :value, :required => true %>
  </div>

  <div class="field">
    <%= f.label :descripcion, "descripción" %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit "enviar", :disable_with => 'enviando..', :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/preferences/index.html.erb
<div class="align_center">
  <h2>preferencias</h2>
</div>

<div class="prefences_on_admin_panel">
  <table>
    <thead>
      <tr>
        <th>Preferencia</th>
        <th>Valor</th>
        <th>Descripción</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @preferences.each do |preferencia| %>
        <tr>
          <td><%= preferencia.key %></td>
          <td><%= preferencia.value %></td>
          <td><%= preferencia.descripcion %></td>
          <td>
            <%= link_to raw("<i class='icon icon-edit icon-white'></i> editar"), edit_admin_preference_path(preferencia), :class => "btn btn-mini btn-info" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="new_preference">
  <%= link_to raw("<i class='icon icon-plus icon-white'></i> añadir preferencia"), new_admin_preference_path, :class => "btn btn-mini btn-info" %>
</div>

app/views/admin/preferences/new.html.erb
<%= render 'form' %>