config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

Qoloquio::Application.routes.draw do

  match '/auth/:provider/callback' => 'users#create' # omniauth
  get "auth/failure" => "home#auth_failure"

  get '/logout' => 'sessions#destroy', as: 'logout'

  # admin path:
  get 'admin' => 'admin#index'

  resources :embedded, only: [:show]

  resources :comments do
    member do
      get :count
    end
  end

  resources :ads do
    member do
      put :visited
    end
  end

  resources :videos do
    member do
      get :tl
    end
  end

  namespace :admin do
    resources :videos, path: "programas" do
      member do
        get :embed
      end
    end
    resources :ads
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :preferences
    resources :segmentos
  end

  # sidekiq:
  mount Sidekiq::Web, at: "/sidekiq_web", :constraints => AdminConstraint.new

  root to: 'home#index'

  match '*a', :to => 'application#routing_error'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :profile

  # relations:
    has_one :facebook_profile, dependent: :destroy
    has_one :twitter_profile, dependent: :destroy
    has_many :comments
    has_many :ads

  # callbacks:
    before_save :set_the_name

  # validations
    validates :profile, :presence => true

  # methods:
    # alias methods:
      def name
        def_profile.name
      end
      def nickname
        def_profile.nickname
      end
      def screen_name
        def_profile.nickname
      end
      def email
        if profile == "facebook"
          def_profile.email
        end
      end
      def image
        def_profile.image
      end
    def default_profile_link
      case self.profile
      when "twitter"
        "http://twitter.com/#{self.screen_name}"
      when "facebook"
        "http://facebook.com/#{self.screen_name}"
      end
    end
    def default_profile_display
      case self.profile
      when "twitter"
        "@#{self.screen_name}"
      when "facebook"
        "(f) #{self.screen_name}"
      end
    end
    def link_to_default_profile
      if self.profile.downcase == "facebook"
        "<a href='#{self.default_profile_link}' target='_blank'>#{self.default_profile_display}</a>"
      elsif self.profile.downcase == "twitter"
        "<a href='#{self.default_profile_link}' target='_blank'>#{self.default_profile_display}</a>"
      end
    end

    def set_the_name
      self.the_name = name + " " + nickname if def_profile
    end

    def def_profile
      if self.read_attribute(:profile) == "twitter"
        @twitter_profile ||= self.twitter_profile
      elsif self.read_attribute(:profile) == "facebook"
        @facebook_profile ||= self.facebook_profile
      else
        raise "only FB and Twitter are supported"
      end
    end

  # class methods:
    def self.create_or_update_from_omniauth( omniauth_hash )
      if omniauth_hash["provider"] == "twitter"
        profile = TwitterProfile.create_or_update( omniauth_hash )
        if profile.new_record?
          user = User.create(profile: "twitter")
          profile.user = user
          profile.save
          return user
        else
          return profile.user
        end
      elsif omniauth_hash["provider"] == "facebook"
        profile = FacebookProfile.create_or_update( omniauth_hash )
        if profile.new_record?
          user = User.create(profile: "facebook")
          profile.user = user
          profile.save
          return user
        else
          return profile.user
        end
      else
        raise "Only FB and twitter are currently supported"
      end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  before_filter :set_place

  def index
    @users = User.order("is_admin DESC, banned DESC").includes(:twitter_profile, :facebook_profile)
    @users = @users.where("the_name LIKE :name", {:name => "%#{params[:search_name]}%"}) unless params[:search_name].blank?
    @users = @users.page(params[:page]).per(10)
  end

  def ban
    @user = User.find(params[:id])
    @user.banned = params[:ban]
    @user.save
    render :user
  end

  def admin
    @user = User.find(params[:id])
    @user.is_admin = params[:be]
    @user.save
    render :user
  end

  private

    def set_place
      @place = "users"
    end
  
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

  def create
    user = User.create_or_update_from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    flash["alert-success"] = "iniciaste sesión como #{current_user.name}"
    redirect_to root_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_index.html.erb
  
  <% @users.each do |user| %>
    <div class="row user user_on_admin_panel_<%= user.id %>">
      <%= render 'user', user: user %>
    </div>
  <% end %>

  <div class="">
    <%= paginate @users, :remote => true %>
  </div>

app/views/admin/users/_user.html.erb
      <a class="span3 align_center ttip user_nickname_container" title="<%= user.name %>" data-placement="left" href="<%= user.default_profile_link %>" target="_blank">
        <div>
          <%= image_tag user.image, :class => "profile_image" %>
        </div>
        <div class="user_nickname_container">
          <small class="user_nickname"><%= user.default_profile_display %></small>
        </div>
      </a>
      <div class="offset1 span7 comment_text">
        <div>
          <% if user.is_admin? %>
            <%= link_to raw("<i class='icon icon-minus-sign'></i> quitar admin"), admin_admin_user_path(user, be: false), :class => "btn btn-mini", :remote => true %>
            <span class="label label-success">admin</span>
          <% else %>
            <%= link_to raw("<i class='icon icon-plus-sign'></i> hacer admin"), admin_admin_user_path(user, be: true), :class => "btn btn-mini", :remote => true %>
          <% end %>
        </div>
        <div>
          <% if user.banned? %>
            <%= link_to raw("<i class='icon icon-minus-sign'></i> ban"), ban_admin_user_path(user, ban: false), :class => "btn btn-mini", :remote => true %>
            <span class="label label-important">baneado</span>
          <% else %>
            <%= link_to raw("<i class='icon icon-plus-sign'></i> ban"), ban_admin_user_path(user, ban: true), :class => "btn btn-mini", :remote => true %>
          <% end %>
        </div>
      </div>

app/views/admin/users/index.html.erb
<div class="align_center">
  <h2>usuarios</h2>
</div>

<div class="input-append">
  <input type="search" placeholder="buscar" id="users_filter_input">
  <span class="add-on"><i class="icon icon-search"></i></span>
</div>

<%= javascript_tag do %>
  $(function () {
    window.Helpers.UsersFilterOnAdminHelper.init();
  });
<% end -%>

<div class="users_on_admin_panel has_padding is_container">
  <%= render 'index' %>
</div>

app/views/admin/users/index.js.erb
$(".users_on_admin_panel").html("<%= j(render('index')) %>");

app/views/admin/users/user.js.erb
$(".user_on_admin_panel_<%= @user.id %>").html("<%= j(render('user', user: @user)) %>");
window.Helpers.Tooltip.init();