config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

Qoloquio::Application.routes.draw do

  match '/auth/:provider/callback' => 'users#create' # omniauth
  get "auth/failure" => "home#auth_failure"

  get '/logout' => 'sessions#destroy', as: 'logout'

  # admin path:
  get 'admin' => 'admin#index'

  resources :embedded, only: [:show]

  resources :comments do
    member do
      get :count
    end
  end

  resources :ads do
    member do
      put :visited
    end
  end

  resources :videos do
    member do
      get :tl
    end
  end

  namespace :admin do
    resources :videos, path: "programas" do
      member do
        get :embed
      end
    end
    resources :ads
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :preferences
    resources :segmentos
  end

  # sidekiq:
  mount Sidekiq::Web, at: "/sidekiq_web", :constraints => AdminConstraint.new

  root to: 'home#index'

  match '*a', :to => 'application#routing_error'
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :poster,
                  :remove_poster,
                  :poster_cache,
                  :iframe_code,
                  :en_vivo_desde,
                  :en_vivo_hasta,
                  :titulo,
                  :descripcion,
                  :segmentos_attributes,
                  :published,
                  :hashtag,
                  :wowza_file_width,
                  :wowza_file_height,
                  :wowza_server,
                  :wowza_app,
                  :wowza_channel,
                  :kind

  mount_uploader :poster, VideoPosterUploader

  # validations:
    validates :titulo, :presence => true
    validate :desde_is_menor_a_hasta

  # relations:
    has_many :comments
    has_many :segmentos, :dependent => :destroy
    accepts_nested_attributes_for :segmentos, :allow_destroy => true

  # methods:
    def desde_is_menor_a_hasta
      unless self.en_vivo_desde < self.en_vivo_hasta
        errors.add :en_vivo_hasta, "debe ser mayor al tiempo en el que empieza"
      end
    end
    def segmento_desde( segmento )
      segmentos = self.segmentos.select([:id, :duracion])
      index = segmentos.index( segmento )
      time = self.en_vivo_desde
      if index and not index === 0
        (0..(index-1)).each do |i|
          time += segmentos[i].duracion.to_i
        end
      end
      time
    end
    def video?
      kind == "Video"
    end
    def audio?
      not video?
    end
    def wowza_file_url
      "rtmp://#{wowza_server}/#{wowza_app}/:#{wowza_channel}"
    end
    def html_url
      "http://#{wowza_server}:1935/#{wowza_app}/mp3:#{wowza_channel}/playlist.m3u8"
    end

end

app/controllers/admin/videos_controller.rb
# encoding: utf-8
class Admin::VideosController < AdminController

  before_filter :set_place
  before_filter :find_video, only: [:edit, :update, :embed]

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
    render :edit
  end

  def edit
  end

  def embed
    @embed_url = app_url + embedded_path(@video)
  end

  def create
    @video = Video.new params[:video]
    if @video.save
      flash["alert-success"] = "programa creado."
      redirect_to action: :index
    else
      flash["alert-error"] = "algo salió mal."
      render :edit
    end
  end

  def update
    if @video.update_attributes(params[:video])
      flash["alert-success"] = "programa actualizado."
      redirect_to action: :index
    else
      flash["alert-error"] = "algo salió mal."
      render :edit
    end
  end

  def destroy
    @video = Video.find params[:id]
    @video.destroy
    redirect_to action: :index
  end

  private

  def find_video
    @video = Video.find params[:id]
  end

  def set_place
    @place = "programas"
  end
end

app/controllers/videos_controller.rb
include ActionView::Helpers::DateHelper

class VideosController < ApplicationController

  def show
    if @video = Video.find_by_id_and_published(params[:id], true)
      render 'home/content_playing'
    else
      render_not_found
      return
    end
  end

  def tl
    segmentos = Segmento.where(video_id: params[:id]).includes(:segmento_urls)
    respond_to do |format|
      format.js {
        time = Time.now
        @segmentos_antes = []
        @segmentos_ahora = []
        @segmentos_despues = []
        segmentos.each do |segmento|
          if segmento.hasta < time
            @segmentos_antes.push segmento.prepare_for_js
          elsif segmento.desde <= time and segmento.hasta >= time
            @segmentos_ahora.push segmento.prepare_for_js
          elsif segmento.desde > time
            @segmentos_despues.push segmento.prepare_for_js
          end
        end
      }
      format.json {
        # segmentos_todos = []
        # segmentos.each do |segmento|
        #   if segmento.has_url?
        #     segmentos_todos.push segmento
        #   end
        # end
        segmentos = segmentos.where("segmento_urls_count > 0")
        segmentos = segmentos.map do |segmento|
          {
            :id => segmento.id,
            :urls => segmento.urls,
            :height => segmento.height,
            :width => segmento.width,
            :titulo => segmento.titulo,
            :duracion => segmento.duracion,
            :duracion_in_words => distance_of_time_in_words( segmento.duracion, 0, true )
          }
        end
        render :json => segmentos
      }
    end
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/videos/_form.html.erb
<div class="is_container">
  <%= nested_form_for [:admin, @video] do |f| %>

    <%= form_errors f.object %>

    <ul class="nav nav-tabs">
      <li class="active"><a href="#informacion" data-toggle="tab">información</a></li>
      <li><a href="#streaming" data-toggle="tab">streaming</a></li>
      <li><a href="#en_vivo" data-toggle="tab">en vivo</a></li>
      <li><a href="#segmentos" data-toggle="tab">segmentos</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="informacion">
        <div class="field">
          <%= f.label :titulo, "título" %>
          <%= f.text_field :titulo, :required => true %>
        </div>

        <div class="field">
          <%= f.label :descripcion, "descripción" %>
          <%= f.text_field :descripcion %>
        </div>

        <div class="field">
          <%= f.label :poster, "póster" %>
          <%= f.file_field :poster %>
          <%= f.hidden_field :poster_cache %>
        </div>

        <% if f.object.poster? %>
          <div class="controls">
            <%= image_tag f.object.poster_url, :class => "image_small" %>
          </div>
          <div class="field">
            <%= f.label :remove_poster, "eliminar póster" %>
            <%= f.check_box :remove_poster %>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :hashtag, "hashtag" %>
          <%= f.text_field :hashtag %>
        </div>

        <div class="field">
          <%= f.label :kind, "Tipo" %>
          <%= f.select :kind, ["Video", "Audio"] %>
        </div>

        <div class="field">
          <%= f.label :published, "publicado (se puede ver off-time)" %>
          <%= f.check_box :published %>
        </div>
      </div>
      <div class="tab-pane" id="streaming">
        <fieldset>
          <legend>streaming con wowza</legend>
          <div class="field">
            <%= f.label :wowza_server, "servidor" %>
            <%= f.text_field :wowza_server, placeholder: "streaming.qoloquio.com" %>
          </div>
          <div class="field">
            <%= f.label :wowza_app, "namespace" %>
            <%= f.text_field :wowza_app, placeholder: "live" %>
          </div>
          <div class="field">
            <%= f.label :wowza_channel, "canal" %>
            <%= f.text_field :wowza_channel, placeholder: "envivo" %>
          </div>
          <div class="field">
            <%= f.label :wowza_file_width, "ancho" %>
            <%= f.number_field :wowza_file_width, :placeholder => "640 (en pixeles)", :min => 0 %>
          </div>
          <div class="field">
            <%= f.label :wowza_file_height, "alto" %>
            <%= f.number_field :wowza_file_height, :placeholder => "480 (en pixeles)", :min => 0 %>
          </div>
        </fieldset>

        <fieldset>
          <legend>streaming de terceros</legend>
          <div class="field">
            <%= f.label :iframe_code, "código del iframe (en vivo)" %>
            <%= f.text_area :iframe_code, :placeholder => "código del iframe que se va a mostrar mientras el programa esté en vivo." %>
          </div>
        </fieldset>
      </div>
      <div class="tab-pane" id="en_vivo">
        <div class="field">
          <%= f.label :en_vivo_desde, "en vivo desde" %>
          <div class="controls">
            <%= f.datetime_select :en_vivo_desde %>
            <% unless f.object.new_record? %>
              <small><span class="help-inline">Si cambias este parámetro, es posible que alteres el orden de los comentarios.</span></small>
            <% end %>
          </div>
        </div>

        <div class="field">
          <%= f.label :en_vivo_hasta, "en vivo hasta" %>
          <div class="controls">
            <%= f.datetime_select :en_vivo_hasta %>
          </div>
        </div>
      </div>
      <div class="tab-pane" id="segmentos">
        <div class="field">
          Segmentos (que se mostrarán en el TL)
          <%= f.fields_for :segmentos do |b| %>
            <%= render 'admin/segmentos/form', f: b %>
          <% end %>
          <div>
            <%= f.link_to_add raw("<i class='icon icon-white icon-plus'></i> agregar segmento"), :segmentos, :class => "btn btn-mini btn-info" %>
          </div>
        </div>
      </div>
    </div>

    <div>
      <%= f.submit "enviar", :disable_with => "enviando..", :class => "btn btn-primary" %>
    </div>

  <% end %>

</div>

<%= link_to raw("<i class='icon icon-white icon-arrow-left'></i> cancelar"), admin_videos_path, :class => "btn btn-inverse btn-mini" %>

app/views/admin/videos/_video.html.erb
    <div class="admin_programa">
      <div class="programa_titulo">
        <%= video.titulo %>
      </div>
      <div class="programa_descripcion">
        <%= video.descripcion %>
      </div>
      <div class="programa_poster">
        <%= image_tag video.poster_url %>
      </div>
      <div class="programa_horario">
        <%= l video.en_vivo_desde, format: :short %> -
        <%= l video.en_vivo_hasta, format: :short %>
        <div>
          <span class="label"><%= video.published ? "publicado" : "no publicado" %></span>
          <span class="label label-info"><%= video.hashtag %></span>
        </div>
      </div>
      <% unless video.segmentos.empty? %>
        <div class="segmentos">
          Segmentos:
          <% video.segmentos.each do |segmento| %>
            <%= render 'admin/segmentos/segmento', segmento: segmento, show_links: true %>
          <% end %>
        </div>
      <% end %>
      <div>
        <%= link_to raw("<i class='icon icon-white icon-pencil'></i> editar"), edit_admin_video_path(video), :class => "btn btn-mini btn-info" %>
        <%= link_to raw("<i class='icon icon-share-alt'></i> embeber"), embed_admin_video_path(video), class: "btn btn-mini btn-default" %>
        <%= link_to raw("<i class='icon icon-remove icon-white'></i> eliminar"), admin_video_path(video), :class => "btn btn-danger btn-mini", method: :delete, :confirm => "¿Seguro?" %>
      </div>
    </div>

app/views/admin/videos/edit.html.erb
<%= render 'form' %>

app/views/admin/videos/embed.html.erb
<div class="align_center">
  <h2><%= @video.titulo %></h2>
</div>

<p>Copia el siguiente código:</p>

<div>
  <pre>
&lt;div id="player"&gt;&lt;/div&gt;
&lt;script type="text/javascript" src="<%= @embed_url %>.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;window.qoloquioElementId = "player";&lt;/script&gt;
  </pre>
</div>

<p>Y pégalo en tu HTML</p>

app/views/admin/videos/index.html.erb
<div class="align_center">
  <h2>programas</h2>
</div>

  <% @videos.each do |video| %>
    <%= render 'video', video: video %>
  <% end %>


<div>
  <%= link_to raw("<i class='icon icon-white icon-plus'></i> añadir un programa"), new_admin_video_path, :class => "btn btn-mini btn-info" %>
</div>