config/routes.rb
require 'sidekiq/web'
require "admin_constraint"

Qoloquio::Application.routes.draw do

  match '/auth/:provider/callback' => 'users#create' # omniauth
  get "auth/failure" => "home#auth_failure"

  get '/logout' => 'sessions#destroy', as: 'logout'

  # admin path:
  get 'admin' => 'admin#index'

  resources :embedded, only: [:show]

  resources :comments do
    member do
      get :count
    end
  end

  resources :ads do
    member do
      put :visited
    end
  end

  resources :videos do
    member do
      get :tl
    end
  end

  namespace :admin do
    resources :videos, path: "programas" do
      member do
        get :embed
      end
    end
    resources :ads
    resources :users do
      member do
        get :admin
        get :ban
      end
    end
    resources :preferences
    resources :segmentos
  end

  # sidekiq:
  mount Sidekiq::Web, at: "/sidekiq_web", :constraints => AdminConstraint.new

  root to: 'home#index'

  match '*a', :to => 'application#routing_error'
end

app/views/layouts/_flashes.html.erb
    <% flash.each do |key, msg| %>
      <%= javascript_tag do %>
        $(function (){
          $.gritter.add({
            title: '',
            text: "<%= msg %>"
          });
        });
      <% end -%>
    <% end %>

app/views/layouts/_foot.html.erb
  <footer>
    <div class="left">
      <div>
        <a href="#">(cc) by-sa-ec-3.0</a>
      </div>
    </div>
    <div class="right">
      <div>
        <a href="#">contacto</a>
      </div>
    </div>
    <div class="left_hidden">
      <div>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/ec/"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/ec/80x15.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">qoloquio</span> se encuentra bajo una <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/ec/">Licencia Creative Commons Atribución-CompartirIgual 3.0 Ecuador</a>.<br />Basada en una obra en <a xmlns:dct="http://purl.org/dc/terms/" href="http://qoloquio.com" rel="dct:source">http://qoloquio.com</a>.
      </div>
      ¿Qué significa esto? Que puedes usar con plena libertad todo el contenido de esta web sin necesidad de pedirnos permiso para compartir, copiar, distribuir, ejecutar y comunicar públicamente estos contenidos, hacer obras derivadas a partir de nuestras fuentes, e inclusive darle un uso comercial a estos contenidos. Lo único que pedimos a cambio es cumplas dos condiciones:
      <ol>
        <li>
          Siempre debes reconocer y citar los créditos del contenido a qoloqio.
        </li>
        <li>
          Si alteras o transformas nuestros contenidos o generas una obra derivada debes distribuir tu nueva obra con una licencia CC idéntica a la que te hemos otorgado
        </li>
      </ol>
Para más info puedes ir a este enlace: http://creativecommons.org/licenses/by-sa/3.0/ec/
    </div>
    <div class="right_hidden">
<p>Para contactarnos con preguntas, anuncios de publicidad, comentarios, sugerencias, puedes dirigirte a:</p>

<p>Correo electrónico: hola@qoloquio.com</p>

<p>Twitter: @qoloquio</p>

<p>FaceBook: <a href="http://facebook.com/qoloquio">/qoloquio</a></p>

<p>Skype: <a href="skype:qoloquio?call">qoloquio</a> (sólo para transmisiones en vivo)</p>

<p><small>No usamos teléfono ni fax, intentamos vivir en el siglo XXI</small></p>
    </div>
  </footer>
</body>
</html>

app/views/layouts/_head.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="author" href="/humans.txt">
  <title>qoloquio &raquo; conversaciones para llevar</title>
  <meta name="description" content="">
  <meta name="author" content="Mario Andrés Correa">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="content_playing">

  <!--[if lt IE 9]><p class=chromeframe>Tu navegador está <strong>obsoleto</strong>. <a href="http://browsehappy.com/">Actualiza a un navegador diferente</a> o <a href="http://www.google.com/chromeframe/?redirect=true">instala google chrome frame</a> (le dará esteroides a tu navegador actual).</p><![endif]-->

  <header>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2 has_logo">
          <%= link_to root_path do %>
            <%= image_tag "/images/qoloquio_logo.png" %>
          <% end %>
        </div>
        <div class="span5 the_name">
          <div class="title"><span class="red">q</span>oloquio</div>
          <div class="subtitle">conversaciones para llevar</div>
        </div>
        <div class="span2 header_session_icons">
          <%= render 'layouts/session' %>
        </div>
        <div class="span3 header_search">
          <input type="search" placeholder="buscar">
        </div>
      </div>
    </div>
  </header>

app/views/layouts/_session.html.erb
<div>
  <%= link_to "skype:qoloquio?call" do %><%= image_tag "/images/SkypeBlue.png", :class => "social_network_logo_login ttip", :title => "llámanos por skype", :data => {:placement => "bottom"} %><% end %>
</div>

<% unless current_user %>
  <div>
    <%= link_to "/auth/facebook" do %><%= image_tag "/images/fblogo.png", :class => "social_network_logo_login ttip", :title => "inicia sesión con facebook", :data => {:placement => "bottom"} %><% end %>
  </div>
  <div>
    <%= link_to "/auth/twitter" do %><%= image_tag "/images/twitterbird.png", :class => "social_network_logo_login ttip", :title => "inicia sesión con twitter", :data => {:placement => "bottom"} %><% end %>
  </div>
<% else %>
  <div>
    <%= image_tag current_user.image, :class => "current_user_profile_image ttip", :title => "has iniciado sesión como #{current_user.name}", :data => {:placement => "bottom"} %><br>
  </div>
  <div>
    <small><%= link_to "salir", logout_path, :class => "ttip", :title => "cerrar sesión", :data => {:placement => "bottom"} %></small>
  </div>
<% end %>

app/views/layouts/admin.html.erb
  
  <%= render 'layouts/head' %>

  <div id="main" class="<%= @is_content_playing ? "" : "has_padding" %>">
    <%= render 'layouts/flashes' %>

    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">Admin panel</a>
        <ul class="nav">
          <li <%= active? "programas" %>>
            <%= link_to "programas", admin_videos_path %>
          </li>
          <li <%= active? "users" %>>
            <%= link_to "usuarios", admin_users_path %>
          </li>
          <li <%= active? "ads" %>>
            <%= link_to "anuncios", admin_ads_path %>
          </li>
          <li <%= active? "preferences" %>>
            <%= link_to "preferencias", admin_preferences_path %>
          </li>
          <li>
            <a href="#">nada</a>
          </li>
          <li>
            <a href="/sidekiq_web">sidekiq</a>
          </li>
        </ul>
      </div>
    </div>

    <div style="padding: 0 1em">
      <%= yield %>
    </div>

  </div>

  <%= render 'layouts/foot' %>

app/views/layouts/application.html.erb
  <%= render 'layouts/head' %>

  <div id="main" class="<%= @is_content_playing ? "" : "has_padding" %>">
    <%= render 'layouts/flashes' %>
    <%= yield %>
  </div>

  <%= render 'layouts/foot' %>

app/views/layouts/static_page_pcworld.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="author" href="/humans.txt">
  <title>qoloquio &raquo; conversaciones para llevar</title>
  <meta name="description" content="">
  <meta name="author" content="Mario Andrés Correa">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="static_landing_page_for_pcworld">

  <div id="main">
    <div class="division">
      <a href="http://qoloquio.com">
        <div>
          <img src="http://qoloquio.com/images/qoloquio_logo.png" id="qoloquio_logo">
        </div>
      </a>
      <em>conversaciones para llevar</em>
    </div>

    <div class="division">
      <h2>estamos proveyendo la plataforma conversacional para el Campus Party Quito 3 #CPQuito3</h2>
    </div>

    <div class="division_2">
      <h4>puedes ver la plataforma en plena acción en <%= link_to "enlinea.pcworld.com.ec", "http://enlinea.pcworld.com.ec", target: "_blank" %></h4>
    </div>

    <div class="division_2">
      <h4>contacto:</h4>
      <p><%= link_to "hola@qoloquio.com", "mailto:hola@qoloquio.com" %></p>
      <div class="the_social_networks">
        <div>
          <%= link_to "http://twitter.com/qoloquio", target: "_blank" do %>
            <%= image_tag "/images/twitterbird.png" %>
            @qoloquio
          <% end %>
        </div>
        <div>
          <%= link_to "http://facebook.com/qoloquio", target: "_blank" do %>
            <%= image_tag "/images/fblogo.png" %>
            /qoloquio
          <% end %>
        </div>
      </div>
    </div>

  </div>


  <script type="text/javascript">
  var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', '51a7751c613f5d1fc1000016');
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();
  </script>
</body>
</html>